version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASES_NAME}
      POSTGRES_USER: ${DATABASES_USER}
      POSTGRES_PASSWORD: ${DATABASES_PASSWORD}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    restart: unless-stopped
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/reminder_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A reminder_app worker -l info -B
    volumes:
      - .:/reminder_app
    depends_on:
      - db
      - redis