# Generated by Django 4.2.14 on 2025-08-19 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    def _postgres_safe_changes(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return
        # Drop reminder_date if it exists
        schema_editor.execute("ALTER TABLE IF EXISTS app_reminder DROP COLUMN IF EXISTS reminder_date;")
        # Add reminder_start_date and reminder_end_date if not exist
        schema_editor.execute("ALTER TABLE app_reminder ADD COLUMN IF NOT EXISTS reminder_start_date timestamptz NULL;")
        schema_editor.execute("ALTER TABLE app_reminder ADD COLUMN IF NOT EXISTS reminder_end_date timestamptz NULL;")
        # Create SendGridDomainAuth table if not exists
        schema_editor.execute(
            """
            CREATE TABLE IF NOT EXISTS app_sendgriddomainauth (
                id BIGSERIAL PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES app_user(id) DEFERRABLE INITIALLY DEFERRED,
                customer_id VARCHAR(255),
                domain VARCHAR(255) NOT NULL,
                domain_id BIGINT,
                subdomain VARCHAR(255) DEFAULT 'mail' NOT NULL,
                is_verified BOOLEAN DEFAULT FALSE NOT NULL,
                dns_records JSONB,
                created_at TIMESTAMPTZ NOT NULL,
                last_checked TIMESTAMPTZ NULL
            );
            """
        )
        # Create ScheduledTask table if not exists
        schema_editor.execute(
            """
            CREATE TABLE IF NOT EXISTS app_scheduledtask (
                id BIGSERIAL PRIMARY KEY,
                task_type VARCHAR(50) NOT NULL,
                task_data JSONB DEFAULT '{}'::jsonb NOT NULL,
                scheduled_at TIMESTAMPTZ NOT NULL,
                executed_at TIMESTAMPTZ NULL,
                is_completed BOOLEAN DEFAULT FALSE NOT NULL,
                created_at TIMESTAMPTZ NOT NULL,
                company_id BIGINT NULL REFERENCES app_company(id) DEFERRABLE INITIALLY DEFERRED
            );
            """
        )
        # Create index if not exists
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS app_schedul_task_ty_bc964d_idx ON app_scheduledtask (task_type, scheduled_at, is_completed);"
        )

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_postgres_safe_changes, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='reminder',
                    name='reminder_date',
                ),
                migrations.AddField(
                    model_name='reminder',
                    name='reminder_end_date',
                    field=models.DateTimeField(blank=True, help_text='Set the end date for recurring reminders', null=True),
                ),
                migrations.AddField(
                    model_name='reminder',
                    name='reminder_start_date',
                    field=models.DateTimeField(blank=True, help_text='Set the start date for the reminders', null=True),
                ),
                migrations.CreateModel(
                    name='SendGridDomainAuth',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('domain', models.CharField(max_length=255)),
                        ('domain_id', models.BigIntegerField(blank=True, null=True)),
                        ('subdomain', models.CharField(blank=True, default='mail', max_length=255)),
                        ('is_verified', models.BooleanField(default=False)),
                        ('dns_records', models.JSONField(blank=True, default=dict, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('last_checked', models.DateTimeField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendgrid_domain_auths', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='ScheduledTask',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('task_type', models.CharField(choices=[('domain_verification', 'Domain Verification'), ('email_reminder', 'Email Reminder'), ('other', 'Other')], max_length=50)),
                        ('task_data', models.JSONField(default=dict)),
                        ('scheduled_at', models.DateTimeField()),
                        ('executed_at', models.DateTimeField(blank=True, null=True)),
                        ('is_completed', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                    ],
                    options={
                        'ordering': ['scheduled_at'],
                        'indexes': [models.Index(fields=['task_type', 'scheduled_at', 'is_completed'], name='app_schedul_task_ty_bc964d_idx')],
                    },
                ),
            ],
        ),
        migrations.AlterField(
            model_name='reminder',
            name='unique_id',
            field=models.CharField(default='', editable=False, max_length=5, unique=True),
        ),
    ]
