# Generated by Django 4.2.14 on 2025-09-18 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reminder_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('domain_verification', 'Domain Verification'), ('gcp_domain_mapping_verification', 'GCP Domain Mapping Verification'), ('site_verification', 'Google Site Verification'), ('email_reminder', 'Email Reminder'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sendgriddomainauth',
            name='dns_records',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sendgriddomainauth',
            name='subdomain',
            field=models.CharField(blank=True, default='mail', max_length=255),
        ),
        migrations.AlterField(
            model_name='sendgriddomainauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendgrid_domain_auths', to=settings.AUTH_USER_MODEL),
        ),
    ]
