# Generated by Django 4.2.14 on 2025-09-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_reminder_completed_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_start_date',
            field=models.DateTimeField(blank=True, help_text='Set when to send the reminder (Send Reminder At)', null=True),
        ),
    ]
