# Generated by Django 4.2.14 on 2025-10-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_drop_legacy_ever_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='visible_to_department',
            field=models.BooleanField(default=False, help_text='When enabled, this reminder will be visible to all members of your department. If unchecked, the reminder will remain private and visible only to you (the creator).'),
        ),
    ]
