# Generated by Django 4.2.14 on 2025-10-03 11:14

import app.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.models.SoftDeleteUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='receiver_email',
            field=models.TextField(help_text='Enter email IDs for reminders, separated by commas.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sender_email',
            field=models.CharField(help_text='Enter the sender email ID', max_length=150),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
