# Generated by Django 4.2.14 on 2025-11-17 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_add_visible_to_department_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique permission code (e.g., 'reminders.create')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=200)),
                ('category', models.CharField(choices=[('reminders', 'Reminders'), ('users', 'Users'), ('departments', 'Departments'), ('company', 'Company Settings'), ('reports', 'Reports'), ('settings', 'System Settings')], help_text='Permission category', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Permission description', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Role name (e.g., 'HR Manager', 'Employee')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted or modified by company admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text="If null, this is a system-wide role. If set, it's company-specific.", null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions assigned to this role', related_name='roles', to='app.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Company context for this role assignment', on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'company'), name='unique_user_role_company'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_role_company'),
        ),
    ]
