# Generated by Django 4.2.14 on 2025-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_user_managers_alter_reminder_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, help_text="Company's primary domain, e.g. 'companydomain.com'", max_length=255, null=True),
        ),
    ]
