# Generated by Django 4.2.14 on 2025-12-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_permission_role_system'),
        ('app', '0020_reminder_slack_user_id'),
    ]

    operations = [
    ]
