# Generated by Django 4.2.14 on 2025-12-07 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_20251207_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='slack_channels',
            field=models.CharField(blank=True, help_text='Comma-separated list of Slack channel IDs or names (e.g. #general, C12345).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='slack_users',
            field=models.ManyToManyField(blank=True, help_text='Additional users to notify via Slack.', related_name='reminder_slack_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
