# Generated by Django 4.2.14 on 2025-12-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_reminder_slack_channels_reminder_slack_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Please set proper meaningful sender name , so that the recipient can understand who has sent this - eg: HR | Company Name,  IT | Company Name, Tech B2B | Company Name, Peter Parker', max_length=200, null=True),
        ),
    ]
