# Generated by Django 4.2.14 on 2025-12-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_reminder_sender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySSOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_endpoint', models.URLField(help_text='IdP Single Sign-On URL (SSO URL)')),
                ('entity_id', models.CharField(help_text='IdP Entity ID (Issuer URL)', max_length=255)),
                ('public_certificate', models.TextField(help_text='IdP X.509 Public Certificate (PEM format)')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_settings', to='app.company')),
            ],
        ),
    ]
