# Generated by Django 4.2.14 on 2026-04-08 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_company_id_alter_companyssosettings_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='users', to='app.department'),
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('data_snapshot', models.JSONField(help_text='Snapshot of reminder data at the time of delivery')),
                ('meta_info', models.JSONField(blank=True, default=dict)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='app.reminder')),
            ],
        ),
        migrations.CreateModel(
            name='JiraIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.URLField(help_text='Jira instance URL (e.g. https://your-domain.atlassian.net)')),
                ('email', models.EmailField(help_text='API Email', max_length=254)),
                ('api_token', models.CharField(help_text='Atlassian API Token', max_length=255)),
                ('project_key', models.CharField(help_text='Default Project Key', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_integration', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='custom_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that can view this reminder.', related_name='visible_reminders', to='app.group'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_group_company'),
        ),
    ]
