# Generated by Django 4.2.14 on 2026-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_user_department_user_departments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-reminder_start_date']},
        ),
        migrations.AlterModelOptions(
            name='reminderdelivery',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['reminder_start_date', 'send', 'active', 'is_deleted'], name='app_reminde_reminde_a7caa8_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['company', 'is_deleted'], name='app_reminde_company_44d8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['created_by', 'is_deleted'], name='app_reminde_created_fc431a_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['unique_id'], name='app_reminde_unique__8e1dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderdelivery',
            index=models.Index(fields=['reminder', 'sent_at'], name='app_reminde_reminde_0bcb95_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderdelivery',
            index=models.Index(fields=['sent_at'], name='app_reminde_sent_at_26ab56_idx'),
        ),
    ]
