# Generated by Django 4.2.14 on 2026-04-08 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_reminder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slack_daily_digest_enabled',
            field=models.BooleanField(default=False, help_text='Enable daily morning Slack notifications listing pending reminders.'),
        ),
        migrations.AddField(
            model_name='company',
            name='slack_digest_channels',
            field=models.CharField(blank=True, help_text='Comma-separated list of Slack channels for digest.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='slack_digest_users',
            field=models.TextField(blank=True, help_text='Comma-separated IDs of users to receive DM digest.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of labels/tags for this reminder.'),
        ),
        migrations.CreateModel(
            name='ReminderAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='reminder_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_attachments', to='app.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='reminders', to='app.reminderattachment'),
        ),
    ]
