# Generated by Django 4.2.14 on 2026-04-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_reminder_approved_at_reminder_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='custom_end_condition',
            field=models.CharField(blank=True, default='never', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='custom_end_occurrences',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='custom_repeat_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='custom_repeat_every',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='custom_repeat_unit',
            field=models.CharField(blank=True, default='week', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='occurrence_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='interval_type',
            field=models.CharField(blank=True, choices=[('one_time', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Annually'), ('weekday', 'Every weekday (Monday to Friday)'), ('custom', 'Custom')], default='one_time', max_length=10, null=True),
        ),
    ]
