# Generated by Django 4.2.14 on 2026-04-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_reminder_custom_end_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='sender_email',
            field=models.CharField(blank=True, help_text='Enter the sender email ID', max_length=150, null=True),
        ),
    ]
