# Generated by Django 4.2.14 on 2026-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_reminder_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_formal',
            field=models.BooleanField(default=False, help_text='Formal reminders are treated as tasks that need to be marked as done.'),
        ),
    ]
