# Generated by Django 4.2.14 on 2026-06-11 09:48

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_reminder_is_formal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraintegration',
            name='api_token',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Atlassian API Token (encrypted at rest)'),
        ),
    ]
