"""
Django settings for dummy project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

AUTH_USER_MODEL = 'app.User'

import os
from pathlib import Path
from decouple import config
import logging



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=os.environ.get('SECRET_KEY', 'change-me-please'))
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS — required in production; start.sh enforces it is set before gunicorn starts.
# In DEBUG mode we relax to all hosts for local development convenience.
_allowed_hosts_default = '*' if DEBUG else ''
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default=_allowed_hosts_default,
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)
if DEBUG and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1', '0.0.0.0']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)

# CSRF_TRUSTED_ORIGINS — REQUIRED in production.
# Comma-separated list of origins that are trusted for POST requests.
# Must include your Cloud Run URL and any custom domain.
# e.g. https://your-service-id.run.app,https://app.yourdomain.com
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000,http://localhost:5173,http://127.0.0.1:5173',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'graphene_django',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # required for BLACKLIST_AFTER_ROTATION
    'oauth2_provider',
    # 'django_celery_beat',  # Commented out for Cloud Run compatibility
    # 'django_celery_results',  # Commented out for Cloud Run compatibility
    'app',
    'auditlog',
    'django_otp',
    'django_otp.plugins.otp_totp',
]

# OTP Settings
OTP_TOTP_SYNC = False
OTP_TOTP_TOLERANCE = 1  # Allow 30s drift


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # For serving static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'app.middleware.SessionUUIDFixerMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'app.middleware.SubdomainMiddleware',
    'app.middleware.DomainVerificationMiddleware',  # Add domain verification middleware
    'app.middleware.TenantRedirectMiddleware',     # Redirect to branded subdomain
    'app.middleware.MessageDedupMiddleware',       # Deduplicate messages server-side
    'app.middleware.IndexBlockMiddleware',         # Block indexing
    'django_otp.middleware.OTPMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'reminder_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Include the compiled React build so Django's TemplateView can serve index.html
        'DIRS': [os.path.join(BASE_DIR, 'frontend', 'dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reminder_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Check if we're using Cloud SQL or local database
if os.environ.get('DB_HOST'):
    # ── Cloud SQL / PostgreSQL ────────────────────────────────────────────────
    # Connection budget:
    #   gunicorn gthread workers open at most 1 connection per thread.
    #   With GUNICORN_WORKERS=2, GUNICORN_THREADS=4 → 8 connections per instance.
    #   Cloud SQL db-f1-micro allows 25 max connections.
    #   At 3+ Cloud Run instances you exceed the limit → OperationalError.
    #
    # Mitigations applied here:
    #   CONN_MAX_AGE=0  — close connections after each request (Cloud Run
    #     containers are short-lived; persistent connections don't help and
    #     can exhaust the pool when scaling).
    #   CONN_HEALTH_CHECKS=True — discard stale connections on reuse.
    #
    # Recommended production fix: use Cloud SQL Auth Proxy + PgBouncer in
    # transaction-mode pooling, or upgrade to db-g1-small (1,000 max conns).
    # Set DB_CONN_MAX_AGE=0 explicitly in Cloud Run env vars.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', ''),
            'USER': os.environ.get('DB_USER', ''),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', ''),
            'PORT': os.environ.get('DB_PORT', '5432'),
            # CONN_MAX_AGE=0: release connections after every request.
            # This is correct for Cloud Run (ephemeral, many instances).
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', 0)),
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                # Limit connections at the psycopg2 level as a backstop.
                # This does NOT replace PgBouncer — it just prevents a single
                # instance from opening more than this many connections.
                # Formula: GUNICORN_WORKERS × GUNICORN_THREADS
                'connect_timeout': 10,
            },
        }
    }
else:
    # Fallback to SQLite for local development or if no DB_HOST is set
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ── Cache ────────────────────────────────────────────────────────────────────
# Redis is REQUIRED in production for:
#   - Rate limiting to work across Cloud Run instances
#   - MFA challenge tokens to be found across instances
#
# In local dev (DEBUG=True) the in-memory fallback is acceptable.
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
elif not DEBUG:
    import warnings
    warnings.warn(
        'REDIS_URL is not set in a non-DEBUG environment. '
        'Rate limiting and MFA tokens will NOT work correctly across '
        'multiple Cloud Run instances. Set REDIS_URL to a shared Redis/Memorystore.',
        RuntimeWarning,
        stacklevel=2,
    )
# else (DEBUG=True, no Redis): LocMemCache is fine for local development.

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# Use simple whitenoise storage for Cloud Run compatibility
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Include the compiled React build assets so collectstatic picks them up.
# frontend/dist/assets/ contains the Vite-compiled JS/CSS bundles.
# Only included if the dist directory actually exists (not present before first build).
_frontend_dist = os.path.join(BASE_DIR, 'frontend', 'dist')
STATICFILES_DIRS = [_frontend_dist] if os.path.isdir(_frontend_dist) else []

# Whitenoise settings for better static file handling
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Graphene (GraphQL) settings
GRAPHENE = {
    'SCHEMA': 'app.schema.schema',
    # DisableIntrospectionMiddleware blocks __schema / __type queries in
    # production.  graphene-django 3.x has no built-in introspection flag —
    # the GRAPHQL_INTROSPECTION setting that was previously here had no effect.
    'MIDDLEWARE': (
        []
        if DEBUG
        else ['app.graphql_middleware.DisableIntrospectionMiddleware']
    ),
    'GRAPHIQL': DEBUG,  # browser IDE only in dev
}

# CORS settings — REQUIRED in production.
# CORS_ALLOWED_ORIGINS: comma-separated list of origins allowed to make
# cross-origin requests (GraphQL, API). Must include your frontend URL.
# e.g. https://app.yourdomain.com,https://your-cloudrun-url.run.app
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Security Headers (Hardening)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Production SSL and Cookies (secure defaults)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
# Ensure cookies are secure in prod or if explicitly requested
if not DEBUG or config('FORCE_SECURE_COOKIES', default=False, cast=bool):
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# TWILIO SETTINGS (FOR SMS)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')


# Celery removed — using Cloud Scheduler + webhook endpoints instead.

#auditlog settings
AUDITLOG_TWO_STEP_MIGRATION = False  # or True, depending on your needs
AUDITLOG_DISABLE_REMOTE_ADDR = True  # or True, depending on your requirements
AUDITLOG_CID_GETTER = None  # Set to the appropriate function or value
AUDITLOG_CID_HEADER = "HTTP_X_CLIENT_ID"  # Set to the HTTP header you use for client identification

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'app': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Django OAuth Toolkit (DOT)
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 1209600,  # 14 days
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 300,
    'ALLOWED_REDIRECT_URI_SCHEMES': ['http', 'https'],
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.OAuthLibCore',
    'PKCE_REQUIRED': True,
    'SCOPES': {
        'read': 'Read access',
        'write': 'Write access',
        'reminders': 'Access reminders',
        'profile': 'Access user profile',
    },
}

# reCAPTCHA settings
RECAPTCHA_ENABLED = config('RECAPTCHA_ENABLED', default=False, cast=bool)
RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY', default='')

# Rate limiting (simple in-memory via Django cache)
RATE_LIMIT_ENABLED = config('RATE_LIMIT_ENABLED', default=True, cast=bool)
RATE_LIMIT_LOGIN_PER_MINUTE = int(config('RATE_LIMIT_LOGIN_PER_MINUTE', default=5))
RATE_LIMIT_SIGNUP_PER_MINUTE = int(config('RATE_LIMIT_SIGNUP_PER_MINUTE', default=3))

# ── Field-level encryption (Jira API token) ───────────────────────────────────
# FIELD_ENCRYPTION_KEY must be a 32-byte Fernet key.
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Set in Cloud Run env vars or .env — if not set a stable dev key is derived
# from SECRET_KEY so local dev works without extra setup.
_raw_encryption_key = os.environ.get('FIELD_ENCRYPTION_KEY', '')
if not _raw_encryption_key:
    # Derive a deterministic key from SECRET_KEY for local dev only.
    # In production, always set FIELD_ENCRYPTION_KEY explicitly.
    import base64, hashlib
    _raw_encryption_key = base64.urlsafe_b64encode(
        hashlib.sha256(SECRET_KEY.encode()).digest()
    ).decode()
FIELD_ENCRYPTION_KEY = _raw_encryption_key

# ── Media files ──────────────────────────────────────────────────────────────
# On Cloud Run, the local filesystem is ephemeral — all uploads are lost on
# restart/redeploy. Use Google Cloud Storage when GCS_BUCKET_NAME is set.
#
# Required env vars for GCS:
#   GCS_BUCKET_NAME       — e.g. "notifyhub-media-prod"
#   GOOGLE_CLOUD_PROJECT  — GCP project ID (or rely on Application Default Credentials)
#
# Local dev (no GCS_BUCKET_NAME): files are written to MEDIA_ROOT as normal.

GCS_BUCKET_NAME = os.environ.get('GCS_BUCKET_NAME', '')

if GCS_BUCKET_NAME:
    # pip install django-storages[google]
    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    GS_BUCKET_NAME = GCS_BUCKET_NAME
    # Files are PRIVATE — the codebase has a serve_protected_media view that
    # enforces authentication before streaming files. Using publicRead here
    # would bypass that check and expose profile pictures / attachments to
    # anyone with the GCS URL.
    GS_DEFAULT_ACL = None                  # no public ACL; bucket default applies
    GS_QUERYSTRING_AUTH = True             # generate short-lived signed URLs
    GS_EXPIRATION = timedelta(minutes=30)  # signed URL lifetime
    GS_FILE_OVERWRITE = False
    # MEDIA_URL is not used directly — serve_protected_media proxies all reads
    # via Django so auth is enforced regardless of storage backend.
    MEDIA_URL = '/media/'
    MEDIA_ROOT = ''                        # not used when GCS is active
else:
    # Local filesystem — fine for development, NOT suitable for production on Cloud Run
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@example.com')

# ── Recurring reminder cleanup ────────────────────────────────────────────────
# Sent reminder rows older than this many days are soft-deleted by the
# cleanup_sent_reminders management command (or the daily webhook).
# Increase for longer audit trails; decrease to keep the table lean.
REMINDER_CLEANUP_DAYS = int(os.environ.get('REMINDER_CLEANUP_DAYS', 90))

# DEFAULT_FROM_EMAIL — must match a SendGrid-authenticated sender domain.
# Set DEFAULT_SENDER_EMAIL in your Cloud Run / .env to the verified address.
# The fallback is a placeholder that will be rejected by SendGrid in production.
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    os.environ.get('DEFAULT_SENDER_EMAIL', 'notifications@notifyhub.app'),
)